apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
      - name: cache
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: cache-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: cache-volume
          mountPath: /var/cache/nginx
      volumes:
      - name: cache-config-volume
        configMap:
          name: cache-config
      - name: cache-volume
        emptyDir: {}
